name: CI

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm install
    - name: Install vue and @vue/compiler-sfc
      run: |
        npm install vue@3.2.13 --save-dev
        npm install @vue/compiler-sfc --save-dev
    - name: Build
      run: npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        repo: https://miloissogood:${{ secrets.forCI }}@github.com/miloissogood/vuePage.git
        ACCESS_TOKEN: ${{ secrets.forCI }}
        BRANCH: gh-pages
        FOLDER: dist